# Generated by Django 3.0.8 on 2020-08-01 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profile', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='user_type',
            field=models.IntegerField(choices=[(1, 'Client'), (2, 'Master')], default=1),
            preserve_default=False,
        ),
    ]
