# Generated by Django 3.1 on 2020-09-13 14:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profile', '0008_auto_20200831_1420'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='profile',
            options={'ordering': ('-id',), 'verbose_name': 'Profile'},
        ),
    ]
