# Generated by Django 3.0.8 on 2020-08-07 17:53

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0003_auto_20200802_1257'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='company',
            name='enter_code',
            field=models.CharField(max_length=5, null=True, unique=True, validators=[django.core.validators.RegexValidator(message='Incorrect enter_code, available symbols (a-z, 0-9)', regex='^[a-z0-9]{5}$')]),
        ),
    ]
