# Generated by Django 3.0.8 on 2020-08-14 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0004_auto_20200807_1753'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='closing_hours',
            field=models.TimeField(null=True),
        ),
        migrations.AddField(
            model_name='company',
            name='opening_hours',
            field=models.TimeField(null=True),
        ),
    ]
