# Generated by Django 3.1 on 2020-09-05 12:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import main.validators


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('company', '0006_auto_20200814_1559'),
    ]

    operations = [
        migrations.RenameField(
            model_name='company',
            old_name='active',
            new_name='is_active',
        ),
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mark', models.DecimalField(decimal_places=1, max_digits=2, validators=[main.validators.validate_feedback_mark])),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='companies_assessment', to=settings.AUTH_USER_MODEL)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feedbacks', to='company.company')),
            ],
            options={
                'unique_together': {('company', 'client')},
            },
        ),
    ]
