# Generated by Django 3.0.8 on 2020-08-01 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reception', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reception',
            name='status',
            field=models.CharField(choices=[('Accepted', 'Accepted'), ('Canceled', 'Canceled')], default='Accepted', max_length=20),
        ),
    ]
