# Generated by Django 3.0.8 on 2020-08-02 12:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('company', '0003_auto_20200802_1257'),
        ('master', '0002_auto_20200801_1645'),
        ('reception', '0002_auto_20200801_1651'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reception',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='client', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='reception',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='company', to='company.Company'),
        ),
        migrations.AlterField(
            model_name='reception',
            name='master',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='master', to='master.Master'),
        ),
    ]
