# Generated by Django 3.1 on 2020-08-14 19:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('master', '0005_auto_20200814_1605'),
        ('reception', '0004_auto_20200803_1253'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reception',
            name='time',
        ),
        migrations.AddField(
            model_name='reception',
            name='end_time',
            field=models.PositiveBigIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='reception',
            name='service',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, related_name='receptions', to='service.service'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='reception',
            name='start_time',
            field=models.PositiveBigIntegerField(db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='reception',
            name='description',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='reception',
            name='status',
            field=models.CharField(choices=[('Accepted', 'Accepted'), ('Canceled', 'Canceled'), ('Booked', 'Booked')], default='Booked', max_length=20),
        ),
    ]
