# Generated by Django 3.1 on 2020-08-14 20:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reception', '0005_auto_20200814_1939'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reception',
            old_name='end_time',
            new_name='end_timestamp',
        ),
        migrations.RenameField(
            model_name='reception',
            old_name='start_time',
            new_name='start_timestamp',
        ),
    ]
