# Generated by Django 3.1 on 2020-09-05 12:26

from django.db import migrations, models
import django.db.models.deletion
import objects.feedback


class Migration(migrations.Migration):

    dependencies = [
        ('reception', '0007_auto_20200831_1418'),
    ]

    operations = [
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mark', models.DecimalField(decimal_places=1, max_digits=2, validators=[objects.feedback.validate_feedback_mark])),
                ('reception', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='feedback', to='reception.reception')),
            ],
        ),
    ]
