# Generated by Django 3.1 on 2020-09-13 14:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reception', '0008_feedback'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='reception',
            options={'ordering': ('-start_timestamp',)},
        ),
    ]
