# Generated by Django 3.1 on 2020-09-23 21:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reception', '0009_auto_20200913_1436'),
    ]

    operations = [
        migrations.AddField(
            model_name='reception',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=7),
        ),
    ]
