# Generated by Django 3.0.8 on 2020-08-01 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0002_auto_20200801_1645'),
        ('master', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='master',
            name='company',
            field=models.ManyToManyField(related_name='masters', to='company.Company'),
        ),
    ]
