# Generated by Django 3.0.8 on 2020-08-14 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('master', '0004_worktypes_duration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='worktypes',
            name='duration',
            field=models.DurationField(),
        ),
    ]
