# Generated by Django 3.1 on 2020-08-31 15:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0004_auto_20200831_1537'),
        ('company', '0006_auto_20200814_1559'),
        ('master', '0005_auto_20200814_1605'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='master',
            name='work_types',
        ),
        migrations.AddField(
            model_name='worktypes',
            name='company',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='company.company'),
        ),
        migrations.AddField(
            model_name='worktypes',
            name='master',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='work_types', to='master.master'),
        ),
        migrations.AddField(
            model_name='worktypes',
            name='price_from',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=7),
        ),
        migrations.AddField(
            model_name='worktypes',
            name='price_to',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=7),
        ),
        migrations.AddField(
            model_name='worktypes',
            name='work_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='service.service'),
        ),
        migrations.AlterUniqueTogether(
            name='worktypes',
            unique_together={('company', 'master', 'work_type')},
        ),
        migrations.RemoveField(
            model_name='worktypes',
            name='name',
        ),
    ]
