# Generated by Django 3.1 on 2020-09-13 14:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0007_auto_20200905_1220'),
        ('service', '0004_auto_20200831_1537'),
        ('master', '0006_auto_20200831_1539'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='WorkTypes',
            new_name='WorkType',
        ),
        migrations.AlterModelOptions(
            name='master',
            options={'ordering': ('-id',)},
        ),
        migrations.RenameField(
            model_name='worktype',
            old_name='work_type',
            new_name='service',
        ),
        migrations.AlterUniqueTogether(
            name='worktype',
            unique_together={('company', 'master', 'service')},
        ),
    ]
